### PR TITLE
v2.0.0

### PR DESCRIPTION
**Pull request by alex-page**
This removes the dependency on creating a personal access token.

### CODE REVIEW

**Comment by MatTheCat** [comment]
Will this PR be merged someday?

**Comment by alex-page** [comment]
@MatTheCat this is currently blocked as GitHubs API doesn't build the website using this set up.

**Comment by MatTheCat** [comment]
Oh okay as this PR was open I assumed it was possible :sweat_smile: 
Do you know if it will be the case in the future?

**Comment by alex-page** [comment]
@MatTheCat I assume so, I am waiting for this to be resolved.

https://github.com/maxheld83/ghpages/pull/18#issuecomment-535651618

**Comment by MatTheCat** [comment]
Crossing my fingers then. Thanks for the explanation!

**Comment by alex-page** [comment]
Closing this PR as no progress has been made. I will re-open it in the future if this changes.

**Pull request closed without merging**
