### PR TITLE
No success log on error

### PR DESCRIPTION
**Pull request by nin-jin**
```
##[error]❌ Failed to deploy to GitHub pages: hyoo/toys/- directory failed to push to gh-pages branch
Error: ENOENT: no such file or directory, stat 'hyoo/toys/-'
✅ Successfully deployed to GitHub pages. The hyoo/toys/- directory has been pushed to gh-pages branch
##[error]Node run failed with exit code 1
```

### CODE REVIEW

**Comment by alex-page** [comment]
Thank you @nin-jin. I will add some version changes and ship this tonight 👍

**Comment by nin-jin** [comment]
So, i can't setup `site-directory` right. Which directory is the base for it?

**Comment by alex-page** [comment]
The default directory is `_site`, you can override it by providing a value:
```yml
        with:
          repo-token: ${{ secrets.GH_PAT }}
          site-directory: "docs"
```

You might have to make sure you are building your website, depending on what project you are using you may need to set up a build script. If your project is open source, I am happy to have a look and try help?

**Comment by nin-jin** [comment]
`_site` is a relative path. Which directory is base for it?

My workflow is here: https://github.com/hyoo-ru/toys.hyoo.ru/blob/master/.github/workflows/deploy.yml

**Comment by alex-page** [comment]
Oh interesting I have never tried deploying from the root directory. I assume you can write: 
```
site-directory: "./"
```

You probably don't need this action you can set up GitHub pages to deploy from the root directory. I think if you select `master branch` in the GitHub pages settings it should work:
Screen Shot 2019-09-23 at 4 14 11 PM

To debug you could install https://www.npmjs.com/package/tree-cli and see what is in the directory you are in.

**Comment by nin-jin** [comment]
I am changing working directory. But base is original directory.

This is works for me:
```
site-directory: '../mam/hyoo/toys/-'
```

**Pull request merged**
